# Site settings
title: ZxBlog
email: zx.bing.oo.gmail.com
description: > # this means to ignore newlines until "baseurl"
  ZxBing的github Blog 小站
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.zxling.cn" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  ZxBingGitHub

# Build settings
markdown: kramdown
highlighter: pygments