# Site settings
title: ZxBing0066's Blog
email: ZxBing0066@gmail.com
description: > # this means to ignore newlines until "baseurl"
  ZxBing的github Blog 小站
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ZxBing0066.com" # the base hostname & protocol for your site
twitter_username: ZxBing0066
github_username:  ZxBing0066

# Build settings
markdown: kramdown

kramdown:
  input: GFM